export const projects = [
  {
    slug: 'hellobooks-ai',
    title: 'HelloBooks.ai',
    description: 'AI-native bookkeeping and accounting product for small and medium businesses, with automated categorization, reconciliation, and reporting.',
    detail: 'HelloBooks.ai was the latest product Nikhil worked on during an internship. It focuses on reducing repetitive bookkeeping work for small and medium businesses through AI-assisted categorization, reconciliation, and reporting.',
    technologies: ['AI', 'Product Development'],
    problem: 'Manual bookkeeping workflows can be repetitive and difficult to keep organized.',
    features: ['Automated categorization', 'Reconciliation workflows', 'Reporting'],
    role: 'Internship project contributor',
    liveUrl: 'https://hellobooks.ai/',
  },
  {
    slug: 'flex-ai-studio',
    title: 'Flex AI Studio 2.0',
    description: 'AI-based no-code portfolio builder with authentication and a dynamic dashboard, built for a Smart India Hackathon internal round.',
    detail: 'Flex AI Studio 2.0 is an AI-assisted no-code portfolio builder created for a Smart India Hackathon internal round, where it received 2nd Runner-Up recognition. The project combines a React-based experience with authentication and dashboard management.',
    technologies: ['MERN', 'React', 'AI'],
    problem: 'Building and maintaining a personal portfolio can require technical setup that many users do not have.',
    features: ['AI-assisted portfolio building', 'Authentication', 'Dynamic dashboard'],
    role: 'Full Stack Developer and hackathon participant',
    githubUrl: 'https://github.com/nikhil-rathour/Flex_ai',
    liveUrl: 'https://flex-ai-red.vercel.app/',
  },
  {
    slug: 'ladhani-estates',
    title: 'Ladhani Estates',
    description: 'Full-stack real estate platform with property management, image uploads, Firebase authentication, PostgreSQL, and a responsive React interface.',
    detail: 'Ladhani Estates is a full-stack real estate platform that brings property management into a responsive React interface. It uses Django REST Framework APIs, Firebase authentication, PostgreSQL, and image upload capabilities.',
    technologies: ['Django', 'Django REST Framework', 'React', 'PostgreSQL', 'Firebase'],
    problem: 'Real estate listings need a structured way to manage properties and present them clearly to users.',
    features: ['Property management', 'Image uploads', 'Firebase authentication', 'REST APIs', 'Responsive React UI'],
    role: 'Full Stack Developer',
    githubUrl: 'https://github.com/nikhil-rathour/ladhani_estates',
    liveUrl: 'https://ladhani-estates-frontend.vercel.app/',
  },
  {
    slug: 'petzone',
    title: 'PetZone',
    description: 'Pet adoption platform with JWT authentication, listings, REST APIs, and a responsive React user interface.',
    detail: 'PetZone is a pet adoption platform created during Hack the Mountains 5.0, where it was recognized as 1st Runner-Up. The project provides authenticated access and listings in a responsive web interface, and has served more than 200 users.',
    technologies: ['React', 'JavaScript', 'JWT', 'REST APIs'],
    problem: 'Pet adoption needs an accessible place for people to discover and manage listings.',
    features: ['JWT authentication', 'Pet listings', 'REST API integration', 'Responsive UI'],
    role: 'Full Stack Developer and hackathon participant',
    githubUrl: 'https://github.com/nikhil-rathour/petzone',
    liveUrl: 'https://petzone-mu.vercel.app/',
  },
  {
    slug: 'uber-clone',
    title: 'Uber Clone',
    description: 'MERN ride-booking application with user authentication, real-time ride status, and administrative features.',
    detail: 'Uber Clone is a MERN full-stack ride-booking application. It brings together user authentication, real-time ride status, and administrative features in a single product experience.',
    technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
    problem: 'Ride-booking services need a clear way to manage user access and ride status.',
    features: ['User authentication', 'Real-time ride status', 'Admin features'],
    role: 'Full Stack Developer',
    liveUrl: 'https://uber-clone-opal.vercel.app/',
  },
  {
    slug: 'ai-code-reviewer',
    title: 'AI Code Reviewer',
    description: 'Real-time code review tool powered by the Google Gemini API and built with React and TypeScript.',
    detail: 'AI Code Reviewer is an LLM-powered tool for real-time code review. It uses React and TypeScript on the client side and connects to the Google Gemini API for AI-assisted feedback.',
    technologies: ['React', 'TypeScript', 'Google Gemini API'],
    problem: 'Developers benefit from quick, contextual feedback while reviewing code.',
    features: ['AI-powered review', 'Real-time feedback', 'Gemini API integration'],
    role: 'Frontend Developer',
    liveUrl: 'https://ai-code-reviewer-ten-ivory.vercel.app/',
  },
  {
    slug: 'ai-chatbot',
    title: 'AI Chatbot',
    description: 'Conversational chatbot built with Next.js, TypeScript, Tailwind CSS, NLP, and LLM-powered APIs.',
    detail: 'AI Chatbot is a conversational web application built with Next.js, TypeScript, and Tailwind CSS. It uses natural language processing and LLM-powered APIs to support its chat experience.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'AI API'],
    problem: 'Conversational interfaces provide a direct way for users to interact with AI capabilities.',
    features: ['Conversational interface', 'Natural language processing', 'LLM-powered API integration'],
    role: 'Frontend Developer',
    liveUrl: 'https://aichatbot-pi-three.vercel.app/',
  },
  {
    slug: 'eventsync',
    title: 'EVENTsync',
    description: 'College club and activity management website with event scheduling and registration.',
    detail: 'EVENTsync is a web application for college clubs and activities. It is designed to streamline event scheduling, registration, and coordination for campus events.',
    technologies: ['React', 'Node.js', 'Express'],
    problem: 'Campus activities need a central place to coordinate events and registrations.',
    features: ['Event scheduling', 'Registration', 'Campus activity management'],
    role: 'Web Developer',
    liveUrl: 'https://eventsync-tafw.onrender.com/',
  },
  {
    slug: 'github-api-search-engine',
    title: 'GitHub API Search Engine',
    description: 'React search interface for GitHub profiles and repositories using the GitHub API.',
    detail: 'GitHub API Search Engine is a React-based mini search engine for exploring GitHub profiles and repositories through the GitHub API.',
    technologies: ['React', 'JavaScript', 'GitHub API'],
    problem: 'GitHub profile and repository data is easier to explore through a focused search experience.',
    features: ['Profile search', 'Repository search', 'GitHub API integration'],
    role: 'Frontend Developer',
    liveUrl: 'https://github-api-rho-two.vercel.app/',
  },
  {
    slug: 'portfolio-website',
    title: 'Portfolio Website',
    description: 'Responsive personal portfolio for presenting projects, experience, skills, and contact details.',
    detail: 'This portfolio website presents Nikhil Rathour’s projects, technical skills, experience, and ways to connect. It is built as a responsive React application with Tailwind CSS and Framer Motion.',
    technologies: ['React', 'Tailwind CSS', 'Framer Motion'],
    problem: 'A personal portfolio needs to make skills, work, and contact information easy for recruiters and collaborators to find.',
    features: ['Project showcase', 'Responsive layout', 'Motion-based interface', 'Contact information'],
    role: 'Designer and Frontend Developer',
    githubUrl: 'https://github.com/nikhil-rathour/portfolio',
    liveUrl: 'https://www.nikhilrathour.in/',
  },
];

export const projectBySlug = (slug) => projects.find((project) => project.slug === slug);
